### ISSUE TITLE
FMUv5 Bootloader in MP Firmware window do not boot up Firmware

### ISSUE THREAD

**Issue by bys1123** [PX4/Bootloader#125]
If open the Mission Planner Firmware Window on PC, then plug a FMUv5 hardware(Pixhawk4, Pixhawk4Mini) on USB port, PWR LED will keep blink, not boot up firmware whether PX4 or Ardupilot.

In FMUv3, it have 5 seconds delay, then will successful boot up. 

Current statue makes lots of users very confuse.

**Comment by Daveuav** [comment]
your pc recognize the fc as px fmu in the list of your hardware peripheral
