### ISSUE TITLE
Newest commit breaks FW upgrade on RDDRONE-FMUK66

### ISSUE THREAD

**Issue by jarivanewijk** [PX4/Bootloader#149]
Seems like the latest commit (3c43ab7) / PR #147 breaks the FW upgrade with QGC on RDDRONE-FMUK66. 

I tried a few builds, everything was working with ddf1d9d but I now get this with the latest commit:
![master](https://user-images.githubusercontent.com/15321907/63860546-9c460000-c9a9-11e9-8f87-814bf5e37090.png)

FYI @davids5 @igalloway

**Comment by davids5** [comment]
Fixed in https://github.com/PX4/Bootloader/commit/d83169d50c333ab33d8206a8a29f6efc9605c39b

**Comment by jarivanewijk** [comment]
Thank you @davids5! I'll try it this week.
