### ISSUE TITLE
Expose the chip serial number in the bootloader

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Bootloader#20]
Currently we can't effectively distinguish between different boards attached to the same host, however, e.g. the safety testing does depend on this. We should expose the serial via the boatloader / USB descriptor.

**Comment by molyswu** [comment]
hello ,I build Bootloader ,then px4flow  load  px4flow-bl.bin for px4flow boarder in  Bootloader(c/px4/Bootloader).the boarder didn't  communicated with PC USB,what's reason?

**Comment by LorenzMeier** [comment]
Done.
