### ISSUE TITLE
Upload bootloader to px4fmu use DFU tools

### ISSUE THREAD

**Issue by YuTingLiu** [PX4/Bootloader#28]
when i use dfu tools to update bootloader ,it's not work
1. GENERATE a DFU file from BIN files,Version ID confused me,In dfu Demo my board Version ID is 2200,so whitch id I generate a DFU file with version id 2100 or 2200 is correct.
2.Etheir Version id 2100 or 2200 have used,replug in after update successful,device as "PX4 FMU" shows in serial port ,then suddenly unshown forever......
3.I have tried Qground to download firmware , qg can found px4 board , but it cann't found bootloader,after i  plug in server times,it finally found and download successful,but still show in serial port a few seconds.

**Comment by LorenzMeier** [comment]
It all works for us.
