### ISSUE TITLE
the px4flow board load px4flow_bl.bin in Bootloader,This problem occurs for ""USB device not recognized" ,is the problem jump to app?

### ISSUE THREAD

**Issue by molyswu** [PX4/Bootloader#29]
hello ,davids5 !
I used STLINK-V2 full chip erase px4flow board  and  build px4  Bootloader file (2015-03-27 Bootloader-master)
, make all Bootloader for px4flow_bl.elf and px4flow-bl.bin , build Successful and connect STLINK-V2 ,then STLINK-V2 program px4flow_bl.bin to px4flow board in Bootloader(c/px4/Bootloader).restart the board  show "USB device not recognized" . the pxflow board
didn't communicated with PC USB, The three LED is lit.
is the problem Bootloader of code  jump to app?Ho to process the problem?

Thank you very much for your help!

Email:sasunwu@126.com
2015-4-1

**Comment by molyswu** [comment]
cdc code :
static void cdc_disconnect(void)
{
	        if (usbd_dev) {
            usbd_disconnect(usbd_dev, true);
            usbd_dev = NULL;
        }
}


--------------------------------------------
main_f4   code:

------------------------
------------------------

if (try_boot) {

#ifdef BOARD_BOOT_FAIL_DETECT
		board_set_rtc_signature(BOOT_RTC_SIGNATURE);
#endif

	jump_to_app();


		timeout = 0;
	}

	
	rcc_clock_setup_hse_3v3(&clock_setup);

	
	cinit(BOARD_INTERFACE_CONFIG);

**Comment by davids5** [comment]
@molyswu I am not familiar with the px4flow board. But I would assume you can debug it with gdb using your Jtag. 

See 
https://pixhawk.org/dev/px4_bootloader
https://pixhawk.org/dev/gdb_cheatsheet
https://pixhawk.org/dev/jtag/start

**Comment by molyswu** [comment]
Checking STM32F407VG  "clock_setup "  with GPIO 12PIN ,13PIN ，voltage only have 0.7V. Righten   voltage have 1.7V on tow PIN。boot cann‘t jump to app.

**Comment by molyswu** [comment]
I was under the windows compiler and debug PX4 Toolchain /eclipse/clonse .
