### ISSUE TITLE
Disable the AHB peripheral clocks

### ISSUE THREAD

**Issue by liangzelang** [PX4/Bootloader#53]
there is a sentence :
RCC_AHB1ENR = 0x00100000; // XXX Magic reset number from STM32F4x reference manual
in the board_init() In the main_f4.c. 
 However ,i found it is wrong after look up the stm32F4xx refence manual.

**Comment by LorenzMeier** [comment]
Could you please instead tell us what you think the correct value is? Why did you look it up in the first place? What problem are you trying to fix?

**Comment by LorenzMeier** [comment]
Can you have a look?

**Comment by liangzelang** [comment]
sorry to forget check your message.   In fact , I don't know what the coder want to do. 
1.    the 20 bit of AHB1ENR  is about CCM data RAM clock.   if you want to disable it  
        RCC_AHB1ENR = 0<<20;
2.  according to the annotate， the coder want to disable the AHB clock.  but  i don't know how to close the clock.

**Comment by davids5** [comment]
![image](https://cloud.githubusercontent.com/assets/1945821/15895648/1f03669e-2d28-11e6-95eb-5823771a0c86.png)

**Comment by liangzelang** [comment]
Got it ， thank U
