### ISSUE TITLE
Need a v5 release

### ISSUE THREAD

**Issue by magicrub** [PX4/Bootloader#57]
per (https://pixhawk.org/dev/bootloader_update) the current release is 2014-02-03 / rev 4.0. Per this commit (https://github.com/PX4/Bootloader/commit/a90981156cc074bfb642013df9dba4c44a4ef2a3) the version was bumped from v4 to v5. If we consider this stable can we get a v5 release please?

**Comment by LorenzMeier** [comment]
Sure, here it is: https://github.com/PX4/Bootloader/releases/tag/v5.0

**Comment by magicrub** [comment]
Does https://pixhawk.org/_media/downloads/px4fmu_bl.bin.zip now point to
this v5 release?
