### ISSUE TITLE
add make auto dependencies 

### ISSUE THREAD

**Issue by davids5** [PX4/Bootloader#77]
Need to add auto dependencies  on header files.

for instance `touch hw_config.h' should cause a rebuild as should editing any other h file in the build.

**Comment by ksschwabe** [comment]
@davids5 @LorenzMeier: I think we can close this issue. It should have been resolved by commit 714a29cf0d47a5fc4689c1427e989afbe6560eee.

**Comment by davids5** [comment]
Closed via  714a29c. Thank you @ksschwabe
