### ISSUE TITLE
Bootloader gets stuck in blocking_handler() when rebooted into bootloader from main application

### ISSUE THREAD

**Issue by ksschwabe** [PX4/Bootloader#81]
I have noticed that when rebooting into the bootloader from the main application, the bootloader seems to get stuck in the blocking_handler(), which is called by the usb_fs_wkup_isr. Only unplugging and replugging the USB cable seems to solve the problem.

Here is the typical scenario that I experience:
1. Using the NSH console on USB. Board registered on /dev/ttyACM0
2. Board powered separately from USB
3. Run the px_uploader.py script with the port as /dev/ttyACM0
4. Board reboots into bootloader (as evidenced by the flashing bootloader LED)
5. Board is reregistered on USB as /dev/ttyACM1
5. The board doesn't respond if try and run px_uploader.py with the port as /dev/ttyACM1
6. Only unplugging and replugging the USB solves the problem.

Any ideas why the bootloader seems to get stuck here? Could it have something to do with an interrupt not being handled correctly?

**Comment by LorenzMeier** [comment]
Is this still persistent?
